# Effect of various national wide factors on prices of US Housing

**Data collection**

# **Problem Statement**

Find publicly available data for critical factors that influence US home prices nationally. Then, build a data science model that explains how these factors have impacted home prices over the last 20 years. Use the S&P Case-Schiller Home Price Index as a proxy for home prices: fred.stlouisfed.org/series/CSUSHPISA

**Business Objective.**

The main business objective is to find which factors are influencing US house prices over past 20 years.

**Approach -**: Data has been collected from different sources and merged into one final dataset based on date.

As a proxy to the home prices(dependent variable), S&P CASE-SHILLER Index is used.

**Sources of Data**
- CASE-SCHILLER Home Price Index - https://fred.stlouisfed.org/series/CSUSHPISA

- Most of the data has been collected from https://fred.stlouisfed.org/

## The Following Factors are Affecting House Prices

1. **Economic Indicators:**
   - **Per Capita GDP (percapitagdp):**
     - This economic indicator reflects the average economic output per person. A higher per capita GDP often correlates with increased purchasing power, potentially influencing the housing market positively.

   - **Personal Income (personalincome):**
     - Personal income levels impact the affordability of housing. Higher personal incomes can lead to increased demand for homes, affecting prices in the housing market.

   - **Unemployment Rate (unemployment rate):**
     - The unemployment rate is a key economic indicator affecting consumer confidence and, consequently, housing demand. Higher unemployment rates may lead to decreased demand and lower home prices.

2. **Interest Rates and Financial Indicators:**
   - **Fed Funds Interest Rate (fedfundsinterest rate):**
     - The Federal Funds Rate influences the cost of borrowing, including mortgage rates. Changes in this rate can impact the accessibility of credit and, subsequently, housing affordability.

   - **Fixed Mortgage 15 Years (fixmortgage15yearsusa):**
     - Mortgage rates, especially fixed-rate mortgages, directly influence housing affordability. Lower fixed mortgage rates can stimulate demand and potentially drive up home prices.

   - **Personal Saving Rate (personalsavingrate):**
     - The personal saving rate reflects consumer saving behavior. A higher saving rate may indicate cautious spending, potentially affecting housing demand and prices.

3. **Labor Market and Demographic Factors:**
   - **Labour Force Participation Rate (labourforceparticipationrate):**
     - The labor force participation rate provides insights into the proportion of the working-age population actively engaged in the labor market. Changes in this rate can impact income levels and housing demand.

   - **Working Population (working population):**
     - The size of the working population influences overall economic activity, affecting housing demand. A growing working population can contribute to increased housing demand and higher prices.

   - **Median Household Income (medianhouseholdincome):**
     - Median household income is a key factor influencing housing affordability. Higher median incomes can support increased demand for homes, potentially driving up prices.

4. **Housing Market and Construction:**
   - **Energy Index (energyindex):**
     - The energy index can indirectly impact housing costs, especially through its influence on construction and maintenance expenses, which may affect overall housing market dynamics.

   - **Construction Spending (constructionspending):**
     - Construction spending reflects investment in new housing projects and infrastructure. Increased construction spending can contribute to a higher housing supply, potentially influencing home prices.

   - **New House Projects (newhouseprojects):**
     - The number of new housing projects provides insights into the future supply of homes. Higher project numbers may suggest an expanding market, affecting housing prices.

5. **Mortgage and Debt Factors:**
   - **Housing Subsidies (housingsubsidies):**
     - Housing subsidies can directly impact the affordability of housing for certain segments of the population, potentially influencing demand and prices in specific market segments.

   - **Delinquency Rate on Mortgage (delinquency rate on mortgage):**
     - The delinquency rate on mortgages reflects the proportion of borrowers facing payment issues. Changes in this rate can indicate financial stress in the market and influence housing prices.

   - **Homes Sold (homessold):**
     - The number of homes sold is a key indicator of market activity. Higher sales volumes may indicate strong demand, potentially contributing to rising home prices.

### Import Libraries

In [ ]:
# Import Libraries
import numpy as np                                                           #numerical computations
import pandas as pd                                                          #to load the data

import warnings
warnings.filterwarnings('ignore')

### Dataset Loading

In [ ]:
# Connecting Google Drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Load CASE-SCHILLER Home Price Index

filepath='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/CSUSHPISA.csv'
df_priceindex=pd.read_csv(filepath)


print(df_priceindex.head())
df_priceindex.shape

         DATE  CSUSHPISA
0  2000-01-01    100.551
1  2000-02-01    101.339
2  2000-03-01    102.127
3  2000-04-01    102.922
4  2000-05-01    103.678

(277, 2)

In [ ]:
# changing the data type of DATE column to datetime
df_priceindex.DATE=pd.to_datetime(df_priceindex.DATE)

# renaming the column CSUSHPISA into priceindex
df_priceindex.rename(columns={'CSUSHPISA': 'priceindex'},inplace=True)

df_priceindex.head()

        DATE  priceindex
0 2000-01-01     100.551
1 2000-02-01     101.339
2 2000-03-01     102.127
3 2000-04-01     102.922
4 2000-05-01     103.678

In [ ]:
df_priceindex.DATE

0     2000-01-01
1     2000-02-01
2     2000-03-01
3     2000-04-01
4     2000-05-01
         ...
272   2022-09-01
273   2022-10-01
274   2022-11-01
275   2022-12-01
276   2023-01-01
Name: DATE, Length: 277, dtype: datetime64[ns]

In [ ]:
# to store all factors in a list
all_factors=[]
# function to load and preprocess data
def load_and_process_data(file_path, date_column_name, oldcolumn,renamedcolumn):
    # Load the data
    df = pd.read_csv(file_path)

    # Display the initial data
    print("Initial Data:")
    print(df.head())

    # Display the data information
    print("\nData Information:")
    print(df.info())

    # Display the shape of the DataFrame
    print("\nDataFrame Shape:", df.shape)

    # Changing the data type of the date column to datetime
    df[date_column_name] = pd.to_datetime(df[date_column_name])

    # Renaming the column
    df.rename(columns={oldcolumn: renamedcolumn}, inplace=True)

    # Display the updated data information
    print("\nUpdated Data Information:")
    print(df.info())


    return df

**Importing Economic factors**

1. percapita GDP
2. Personal Income
3. Unemployment rate

In [ ]:
# Querterly Percapita GDP
filepath='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/percapitagdp.csv'
df_percapitagdp=pd.read_csv(filepath)


print(df_percapitagdp.head())
print(df_percapitagdp.info())
df_percapitagdp.shape

         DATE  A939RX0Q048SBEA
0  2000-01-01          49335.0
1  2000-04-01          50109.0
2  2000-07-01          50024.0
3  2000-10-01          50190.0
4  2001-01-01          49911.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DATE             93 non-null     object
 1   A939RX0Q048SBEA  93 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.6+ KB
None

(93, 2)

In [ ]:
# changing the data type of DATE column to datetime
df_percapitagdp.DATE=pd.to_datetime(df_percapitagdp.DATE)

# renaming the column CSUSHPISA into priceindex
df_percapitagdp.rename(columns={'A939RX0Q048SBEA': 'percapitagdp'},inplace=True)

df_percapitagdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DATE          93 non-null     datetime64[ns]
 1   percapitagdp  93 non-null     float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 1.6 KB

In [ ]:
all_factors.append(df_percapitagdp)

In [ ]:
df_percapitagdp.DATE

0    2000-01-01
1    2000-04-01
2    2000-07-01
3    2000-10-01
4    2001-01-01
        ...
88   2022-01-01
89   2022-04-01
90   2022-07-01
91   2022-10-01
92   2023-01-01
Name: DATE, Length: 93, dtype: datetime64[ns]

In [ ]:
#Monthly personal income from 2003

filepath='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/PersonalIncome.csv'
df_personalincome=pd.read_csv(filepath)


print(df_personalincome.head())
print(df_personalincome.info())
print(df_personalincome.DATE)
df_personalincome.shape

         DATE  DSPIC96
0  2003-01-01  10710.4
1  2003-02-01  10674.0
2  2003-03-01  10696.5
3  2003-04-01  10752.7
4  2003-05-01  10832.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DATE     241 non-null    object
 1   DSPIC96  241 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.9+ KB
None
0      2003-01-01
1      2003-02-01
2      2003-03-01
3      2003-04-01
4      2003-05-01
          ...
236    2022-09-01
237    2022-10-01
238    2022-11-01
239    2022-12-01
240    2023-01-01
Name: DATE, Length: 241, dtype: object

(241, 2)

In [ ]:
# changing the data type of DATE column to datetime
df_personalincome.DATE=pd.to_datetime(df_personalincome.DATE)

# renaming the column DSPIC96 into personalincome
df_personalincome.rename(columns={'DSPIC96': 'personalincome'},inplace=True)

df_personalincome.info()
all_factors.append(df_personalincome)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   DATE            241 non-null    datetime64[ns]
 1   personalincome  241 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 3.9 KB

In [ ]:
# Reading Unemployment Rate Data into a dataframe
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/UNRATE.csv'
date_column = 'DATE'
oldcolumn = 'UNRATE'
renamedcolumn='unemprate'


df_unemprate = load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_unemprate)

Initial Data:
         DATE  UNRATE
0  2000-01-01     4.0
1  2000-02-01     4.1
2  2000-03-01     4.0
3  2000-04-01     3.8
4  2000-05-01     4.0

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DATE    277 non-null    object
 1   UNRATE  277 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.5+ KB
None

DataFrame Shape: (277, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DATE       277 non-null    datetime64[ns]
 1   unemprate  277 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.5 KB
None

**Interest Rates and Financial Indicators:**

1.Fed Funds Interest Rate

2.Fixed Mortgage 15 Years

3.Personal Saving Rate

In [ ]:
# Reading monthly fed funds interest Rate Data into a dataframe(2000-2023)
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/FEDFUNDS_Interestrate.csv'
date_column = 'DATE'
oldcolumn = 'FEDFUNDS'
renamedcolumn='fedfundsinterestrate'


df_fedfundinterestrate = load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_fedfundinterestrate)

Initial Data:
         DATE  FEDFUNDS
0  2000-01-01      5.45
1  2000-02-01      5.73
2  2000-03-01      5.85
3  2000-04-01      6.02
4  2000-05-01      6.27

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DATE      277 non-null    object
 1   FEDFUNDS  277 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.5+ KB
None

DataFrame Shape: (277, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   DATE                  277 non-null    datetime64[ns]
 1   fedfundsinterestrate  277 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.5 KB
None

In [ ]:
# Reading monthly fixed Mortgage 15years US Data into a dataframe(2000-2023)
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/FIXMORTGAGE15US.csv'
date_column = 'DATE'
oldcolumn = 'MORTGAGE15US'
renamedcolumn='fixmortgagerate15years'


df_fixmortgage15 = load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_fixmortgage15)

Initial Data:
         DATE  MORTGAGE15US
0  2000-01-01        7.8025
1  2000-02-01        7.9325
2  2000-03-01        7.8320
3  2000-04-01        7.8000
4  2000-05-01        8.1825

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DATE          277 non-null    object
 1   MORTGAGE15US  277 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.5+ KB
None

DataFrame Shape: (277, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   DATE                    277 non-null    datetime64[ns]
 1   fixmortgagerate15years  277 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.5 KB
None

In [ ]:
# Reading Personal saving rate Data into a dataframe(2000-2023)
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/personal_saving_rate.csv'
date_column = 'DATE'
oldcolumn = 'PSAVERT'
renamedcolumn='personalsavingrate'


df_personalsavingrate = load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_personalsavingrate)

Initial Data:
         DATE  PSAVERT
0  2000-01-01      4.5
1  2000-02-01      4.0
2  2000-03-01      3.8
3  2000-04-01      4.3
4  2000-05-01      4.3

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DATE     277 non-null    object
 1   PSAVERT  277 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.5+ KB
None

DataFrame Shape: (277, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                277 non-null    datetime64[ns]
 1   personalsavingrate  277 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.5 KB
None

**Labor Market and Demographic Factors:**

1.Labour Force Participation Rate

2.Working Population

3.Median Household Income

In [ ]:
# Reading labor fore participation rate Data into a dataframe(2000-2023)
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/labour_force_participation_rate.csv'
date_column = 'DATE'
oldcolumn = 'CIVPART'
renamedcolumn='laborforceparticipationrate'


df_lfpr = load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_lfpr)

Initial Data:
         DATE  CIVPART
0  2000-01-01     67.3
1  2000-02-01     67.3
2  2000-03-01     67.3
3  2000-04-01     67.3
4  2000-05-01     67.1

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DATE     277 non-null    object
 1   CIVPART  277 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.5+ KB
None

DataFrame Shape: (277, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   DATE                         277 non-null    datetime64[ns]
 1   laborforceparticipationrate  277 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.5 KB
None

In [ ]:
# Reading working population Data into a dataframe(2000-2023)
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/working_population.csv'
date_column = 'DATE'
oldcolumn = 'LFWA64TTUSM647S'
renamedcolumn='workingpopulation'


df_workingpop = load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_workingpop)

Initial Data:
         DATE  LFWA64TTUSM647S
0  2000-01-01     1.782921e+08
1  2000-02-01     1.783433e+08
2  2000-03-01     1.784055e+08
3  2000-04-01     1.785807e+08
4  2000-05-01     1.787272e+08

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DATE             277 non-null    object
 1   LFWA64TTUSM647S  277 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.5+ KB
None

DataFrame Shape: (277, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   DATE               277 non-null    datetime64[ns]
 1   workingpopulation  277 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.5 KB
None

In [ ]:
df_workingpop.head()

        DATE  workingpopulation
0 2000-01-01       1.782921e+08
1 2000-02-01       1.783433e+08
2 2000-03-01       1.784055e+08
3 2000-04-01       1.785807e+08
4 2000-05-01       1.787272e+08

In [ ]:
# Reading yearly Median household income Data into a dataframe(2000-2023)
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/MEHOINUSA672N.csv'
date_column = 'DATE'
oldcolumn = 'MEHOINUSA672N'
renamedcolumn='medianhouseincome'


df_medianhouseincome = load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_medianhouseincome)

Initial Data:
         DATE  MEHOINUSA672N
0  2000-01-01          67470
1  2001-01-01          66360
2  2002-01-01          65820
3  2003-01-01          65860
4  2004-01-01          65760

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE           23 non-null     object
 1   MEHOINUSA672N  23 non-null     int64
dtypes: int64(1), object(1)
memory usage: 496.0+ bytes
None

DataFrame Shape: (23, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   DATE               23 non-null     datetime64[ns]
 1   medianhouseincome  23 non-null     int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 496.0 bytes
None

**Housing Market and Construction:**

1.Energy Index

2.Construction Spending

3.New House Projects (newhouseprojects):

In [ ]:
# Reading monthly Energy Data into a dataframe(2000-2023)
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/energyindex.csv'
date_column = 'DATE'
oldcolumn = 'PNRGINDEXM'
renamedcolumn='energyindex'


df_energyindex = load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_energyindex)

Initial Data:
         DATE  PNRGINDEXM
0  2000-01-01   62.239226
1  2000-02-01   66.423300
2  2000-03-01   66.685116
3  2000-04-01   61.416955
4  2000-05-01   68.671469

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   DATE        277 non-null    object
 1   PNRGINDEXM  277 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.5+ KB
None

DataFrame Shape: (277, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE         277 non-null    datetime64[ns]
 1   energyindex  277 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.5 KB
None

In [ ]:
# Reading monthly total construction spending Data into a dataframe(2000-2023)
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/totalconstructionspending.csv'
date_column = 'DATE'
oldcolumn = 'TTLCONS'
renamedcolumn='constructionspending'


df_totalconstructionspend = load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_totalconstructionspend)

Initial Data:
         DATE   TTLCONS
0  2000-01-01  784940.0
1  2000-02-01  793737.0
2  2000-03-01  809459.0
3  2000-04-01  804766.0
4  2000-05-01  805005.0

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DATE     277 non-null    object
 1   TTLCONS  277 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.5+ KB
None

DataFrame Shape: (277, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   DATE                  277 non-null    datetime64[ns]
 1   constructionspending  277 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.5 KB
None

In [ ]:
# Reading monthly New house projects Data into a dataframe(2000-2023)
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/Total_completed_newhouseunits.csv'
date_column = 'DATE'
oldcolumn = 'COMPUTSA'
renamedcolumn='totalnewhouseunits'


df_tnewhouseunits = load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_tnewhouseunits)

Initial Data:
         DATE  COMPUTSA
0  2000-01-01    1574.0
1  2000-02-01    1677.0
2  2000-03-01    1704.0
3  2000-04-01    1610.0
4  2000-05-01    1682.0

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DATE      277 non-null    object
 1   COMPUTSA  277 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.5+ KB
None

DataFrame Shape: (277, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                277 non-null    datetime64[ns]
 1   totalnewhouseunits  277 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 4.5 KB
None

**Other factors:**

1.Housing Subsidies

2.Delinquency Rate on Mortgage

3.Total house units

In [ ]:
# Reading yearly housing subsidies Data into a dataframe(2000-2023)
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/housingsubsidies.csv'
date_column = 'DATE'
oldcolumn = 'L312051A027NBEA'
renamedcolumn='housingsubsidies'


df_housingsubsidies = load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_housingsubsidies)

Initial Data:
         DATE  L312051A027NBEA
0  2000-01-01           19.690
1  2001-01-01           20.573
2  2002-01-01           24.183
3  2003-01-01           25.930
4  2004-01-01           27.201

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DATE             23 non-null     object
 1   L312051A027NBEA  23 non-null     float64
dtypes: float64(1), object(1)
memory usage: 496.0+ bytes
None

DataFrame Shape: (23, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   DATE              23 non-null     datetime64[ns]
 1   housingsubsidies  23 non-null     float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 496.0 bytes
None

In [ ]:
# Reading total househols units Data into a dataframe(2000-2023)
file_path='/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/totalhouseholdunits.csv'
date_column = 'DATE'
oldcolumn = 'TTLHH'
renamedcolumn='totalhouseholds'


df_totalhouseholdunits= load_and_process_data(file_path, date_column, oldcolumn,renamedcolumn)
all_factors.append(df_totalhouseholdunits)

Initial Data:
         DATE     TTLHH
0  2000-01-01  104705.0
1  2001-01-01  108209.0
2  2002-01-01  109297.0
3  2003-01-01  111278.0
4  2004-01-01  112000.0

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DATE    24 non-null     object
 1   TTLHH   24 non-null     float64
dtypes: float64(1), object(1)
memory usage: 512.0+ bytes
None

DataFrame Shape: (24, 2)

Updated Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   DATE             24 non-null     datetime64[ns]
 1   totalhouseholds  24 non-null     float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 512.0 bytes
None

In [ ]:
#Merging all factors

# List of DataFrames
dfs = [df_priceindex,df_percapitagdp, df_personalincome, df_unemprate, df_fedfundinterestrate, df_fixmortgage15, df_personalsavingrate, df_lfpr, df_workingpop, df_medianhouseincome, df_energyindex, df_totalconstructionspend, df_tnewhouseunits, df_housingsubsidies, df_totalhouseholdunits]

# Merging DataFrames based on 'DATE'
merged_df = dfs[0]  # Initialize with the first DataFrame

# Loop through the remaining DataFrames and merge
for df in dfs[1:]:
    merged_df = pd.merge(merged_df, df, on='DATE', how='left')

# Display the merged DataFrame
print(merged_df.shape)
merged_df.head(25)

(277, 16)

,DATE,priceindex,percapitagdp,personalincome,unemprate,fedfundsinterestrate,fixmortgagerate15years,personalsavingrate,laborforceparticipationrate,workingpopulation,medianhouseincome,energyindex,constructionspending,totalnewhouseunits,housingsubsidies,totalhouseholds
0,2000-01-01,100.551,49335.0,NaN,4.0,5.45,7.8025,4.5,67.3,1.782921e+08,67470.0,62.239226,784940.0,1574.0,19.690,104705.0
1,2000-02-01,101.339,NaN,NaN,4.1,5.73,7.9325,4.0,67.3,1.783433e+08,NaN,66.423300,793737.0,1677.0,NaN,NaN
2,2000-03-01,102.127,NaN,NaN,4.0,5.85,7.8320,3.8,67.3,1.784055e+08,NaN,66.685116,809459.0,1704.0,NaN,NaN
3,2000-04-01,102.922,50109.0,NaN,3.8,6.02,7.8000,4.3,67.3,1.785807e+08,NaN,61.416955,804766.0,1610.0,NaN,NaN
4,2000-05-01,103.678,NaN,NaN,4.0,6.27,8.1825,4.3,67.1,1.787272e+08,NaN,68.671469,805005.0,1682.0,NaN,NaN
5,2000-06-01,104.424,NaN,NaN,4.0,6.53,7.9920,4.3,67.1,1.790565e+08,NaN,75.150707,795411.0,1530.0,NaN,NaN
6,2000-07-01,105.054,50024.0,NaN,4.0,6.54,7.8650,4.7,66.9,1.793240e+08,NaN,72.686554,783795.0,1495.0,NaN,NaN
7,2000-08-01,105.768,NaN,NaN,4.1,6.50,7.7625,4.8,66.9,1.793947e+08,NaN,76.799195,805341.0,1573.0,NaN,NaN
8,2000-09-01,106.538,NaN,NaN,3.9,6.52,7.6040,4.1,66.9,1.795656e+08,NaN,82.934811,814330.0,1528.0,NaN,NaN
9,2000-10-01,107.382,50190.0,NaN,3.9,6.51,7.4700,4.3,66.8,1.797542e+08,NaN,82.305584,816100.0,1513.0,NaN,NaN
10,2000-11-01,108.302,NaN,NaN,3.9,6.51,7.4175,4.3,66.9,1.799285e+08,NaN,84.812516,820054.0,1539.0,NaN,NaN
11,2000-12-01,109.140,NaN,NaN,3.9,6.40,7.0560,4.1,67.0,1.801391e+08,NaN,83.320757,811516.0,1521.0,NaN,NaN
12,2001-01-01,109.846,49911.0,NaN,4.2,5.98,6.6400,4.5,67.2,1.804166e+08,66360.0,82.367105,814479.0,1456.0,20.573,108209.0
13,2001-02-01,110.500,NaN,NaN,4.2,5.49,6.6400,4.6,67.1,1.805777e+08,NaN,76.511028,813647.0,1536.0,NaN,NaN
14,2001-03-01,111.109,NaN,NaN,4.3,5.31,6.5080,4.9,67.2,1.806361e+08,NaN,72.127031,828057.0,1470.0,NaN,NaN
15,2001-04-01,111.652,50105.0,NaN,4.4,4.80,6.5950,4.8,66.9,1.809055e+08,NaN,73.105310,842392.0,1574.0,NaN,NaN
16,2001-05-01,112.164,NaN,NaN,4.3,4.21,6.6750,4.3,66.7,1.810146e+08,NaN,73.018054,848146.0,1497.0,NaN,NaN
17,2001-06-01,112.796,NaN,NaN,4.5,3.97,6.7000,4.2,66.7,1.813565e+08,NaN,70.771303,855730.0,1654.0,NaN,NaN
18,2001-07-01,113.491,49774.0,NaN,4.6,3.77,6.6825,5.4,66.8,1.816143e+08,NaN,64.647998,850471.0,1582.0,NaN,NaN
19,2001-08-01,114.167,NaN,NaN,4.9,3.65,6.5000,6.5,66.5,1.818285e+08,NaN,65.747883,847465.0,1615.0,NaN,NaN
20,2001-09-01,114.812,NaN,NaN,5.0,3.07,6.3400,6.9,66.8,1.820565e+08,NaN,62.873257,837412.0,1551.0,NaN,NaN
21,2001-10-01,115.310,49783.0,NaN,5.3,2.49,6.0975,2.9,66.7,1.822366e+08,NaN,55.517126,845941.0,1599.0,NaN,NaN
22,2001-11-01,115.857,NaN,NaN,5.5,2.09,6.1460,3.4,66.7,1.824306e+08,NaN,50.123735,843911.0,1555.0,NaN,NaN
23,2001-12-01,116.455,NaN,NaN,5.7,1.82,6.5425,3.7,66.7,1.826419e+08,NaN,49.467831,849689.0,1693.0,NaN,NaN
24,2002-01-01,117.144,50091.0,NaN,5.7,1.73,6.4800,5.6,66.5,1.825664e+08,65820.0,49.446172,858654.0,1632.0,24.183,109297.0

In [ ]:
# Filter rows where 'DATE' is greater than or equal to '2003-01-01' because personal income data is available from 2003 only.
merged_df_2003 = merged_df[merged_df['DATE'] >= '2003-01-01']

merged_df_2003.head(15)

,DATE,priceindex,percapitagdp,personalincome,unemprate,fedfundsinterestrate,fixmortgagerate15years,personalsavingrate,laborforceparticipationrate,workingpopulation,medianhouseincome,energyindex,constructionspending,totalnewhouseunits,housingsubsidies,totalhouseholds
36,2003-01-01,128.461,50462.0,10710.4,5.8,1.24,5.3040,5.3,66.4,1.856353e+08,65860.0,79.454166,863855.0,1654.0,25.930,111278.0
37,2003-02-01,129.355,NaN,10674.0,5.9,1.26,5.2200,5.2,66.4,1.858697e+08,NaN,90.889264,859225.0,1688.0,NaN,NaN
38,2003-03-01,130.148,NaN,10696.5,5.9,1.25,5.0650,4.9,66.3,1.860851e+08,NaN,80.592195,851132.0,1638.0,NaN,NaN
39,2003-04-01,130.884,50796.0,10752.7,6.0,1.26,5.1175,5.0,66.4,1.864708e+08,NaN,70.847197,859459.0,1662.0,NaN,NaN
40,2003-05-01,131.735,NaN,10832.0,6.1,1.26,4.8600,5.3,66.4,1.866491e+08,NaN,72.878676,866814.0,1733.0,NaN,NaN
41,2003-06-01,132.649,NaN,10860.6,6.3,1.22,4.6275,5.1,66.5,1.868007e+08,NaN,76.204120,880865.0,1641.0,NaN,NaN
42,2003-07-01,133.777,51512.0,10991.1,6.2,1.01,4.9675,5.9,66.2,1.870665e+08,NaN,75.261384,891264.0,1680.0,NaN,NaN
43,2003-08-01,134.969,NaN,11066.7,6.1,1.03,5.5880,5.7,66.1,1.873040e+08,NaN,77.177782,901839.0,1570.0,NaN,NaN
44,2003-09-01,136.294,NaN,10940.8,6.1,1.01,5.4575,4.9,66.1,1.875390e+08,NaN,71.984238,911589.0,1719.0,NaN,NaN
45,2003-10-01,137.531,51986.0,10982.3,6.0,1.01,5.2740,5.0,66.1,1.877385e+08,NaN,75.717675,925732.0,1728.0,NaN,NaN
46,2003-11-01,138.794,NaN,11048.4,5.8,1.00,5.2725,5.0,66.1,1.879724e+08,NaN,75.940250,925985.0,1692.0,NaN,NaN
47,2003-12-01,140.179,NaN,11057.2,5.7,0.98,5.2040,5.0,65.9,1.881361e+08,NaN,82.273735,948491.0,1716.0,NaN,NaN
48,2004-01-01,141.646,52179.0,11051.2,5.7,1.00,5.0150,4.6,66.1,1.876888e+08,65760.0,85.615384,938525.0,1709.0,27.201,112000.0
49,2004-02-01,143.192,NaN,11071.0,5.6,1.01,4.9375,4.6,66.0,1.878760e+08,NaN,83.783437,937813.0,1718.0,NaN,NaN
50,2004-03-01,145.059,NaN,11115.6,5.8,1.00,4.7400,4.5,66.0,1.880582e+08,NaN,86.843360,961159.0,1794.0,NaN,NaN

In [ ]:
# Reset the index
merged_df_2003 = merged_df_2003.reset_index(drop=True)

merged_df_2003.head(10)

,DATE,priceindex,percapitagdp,personalincome,unemprate,fedfundsinterestrate,fixmortgagerate15years,personalsavingrate,laborforceparticipationrate,workingpopulation,medianhouseincome,energyindex,constructionspending,totalnewhouseunits,housingsubsidies,totalhouseholds
0,2003-01-01,128.461,50462.0,10710.4,5.8,1.24,5.3040,5.3,66.4,1.856353e+08,65860.0,79.454166,863855.0,1654.0,25.93,111278.0
1,2003-02-01,129.355,NaN,10674.0,5.9,1.26,5.2200,5.2,66.4,1.858697e+08,NaN,90.889264,859225.0,1688.0,NaN,NaN
2,2003-03-01,130.148,NaN,10696.5,5.9,1.25,5.0650,4.9,66.3,1.860851e+08,NaN,80.592195,851132.0,1638.0,NaN,NaN
3,2003-04-01,130.884,50796.0,10752.7,6.0,1.26,5.1175,5.0,66.4,1.864708e+08,NaN,70.847197,859459.0,1662.0,NaN,NaN
4,2003-05-01,131.735,NaN,10832.0,6.1,1.26,4.8600,5.3,66.4,1.866491e+08,NaN,72.878676,866814.0,1733.0,NaN,NaN
5,2003-06-01,132.649,NaN,10860.6,6.3,1.22,4.6275,5.1,66.5,1.868007e+08,NaN,76.204120,880865.0,1641.0,NaN,NaN
6,2003-07-01,133.777,51512.0,10991.1,6.2,1.01,4.9675,5.9,66.2,1.870665e+08,NaN,75.261384,891264.0,1680.0,NaN,NaN
7,2003-08-01,134.969,NaN,11066.7,6.1,1.03,5.5880,5.7,66.1,1.873040e+08,NaN,77.177782,901839.0,1570.0,NaN,NaN
8,2003-09-01,136.294,NaN,10940.8,6.1,1.01,5.4575,4.9,66.1,1.875390e+08,NaN,71.984238,911589.0,1719.0,NaN,NaN
9,2003-10-01,137.531,51986.0,10982.3,6.0,1.01,5.2740,5.0,66.1,1.877385e+08,NaN,75.717675,925732.0,1728.0,NaN,NaN

In [ ]:
print(merged_df_2003.shape)
merged_df_2003.info()

(241, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   DATE                         241 non-null    datetime64[ns]
 1   priceindex                   241 non-null    float64
 2   percapitagdp                 81 non-null     float64
 3   personalincome               241 non-null    float64
 4   unemprate                    241 non-null    float64
 5   fedfundsinterestrate         241 non-null    float64
 6   fixmortgagerate15years       241 non-null    float64
 7   personalsavingrate           241 non-null    float64
 8   laborforceparticipationrate  241 non-null    float64
 9   workingpopulation            241 non-null    float64
 10  medianhouseincome            20 non-null     float64
 11  energyindex                  241 non-null    float64
 12  constructionspending         241 non-null    float64
 13  totalnewhouseunits           241 non-null    float64
 14  housingsubsidies             20 non-null     float64
 15  totalhouseholds              21 non-null     float64
dtypes: datetime64[ns](1), float64(15)
memory usage: 30.2 KB

percapitagdp has quarterly data, medianhouseincome, housesubsidies and total house units have yearly data.

In [ ]:

# Upsample/Interpolate for 'percapitagdp'
merged_df_2003['percapitagdp'] = merged_df_2003['percapitagdp'].interpolate()
merged_df_2003.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   DATE                         241 non-null    datetime64[ns]
 1   priceindex                   241 non-null    float64
 2   percapitagdp                 241 non-null    float64
 3   personalincome               241 non-null    float64
 4   unemprate                    241 non-null    float64
 5   fedfundsinterestrate         241 non-null    float64
 6   fixmortgagerate15years       241 non-null    float64
 7   personalsavingrate           241 non-null    float64
 8   laborforceparticipationrate  241 non-null    float64
 9   workingpopulation            241 non-null    float64
 10  medianhouseincome            20 non-null     float64
 11  energyindex                  241 non-null    float64
 12  constructionspending         241 non-null    float64
 13  totalnewhouseunits           241 non-null    float64
 14  housingsubsidies             20 non-null     float64
 15  totalhouseholds              21 non-null     float64
dtypes: datetime64[ns](1), float64(15)
memory usage: 30.2 KB

In [ ]:
df1=merged_df_2003.copy()

In [ ]:
# Downsampling/Averaging for other columns
columns_to_downsample = ['medianhouseincome', 'housingsubsidies', 'totalhouseholds']

for column in columns_to_downsample:
    df1[column] = df1[column].groupby(df1['DATE'].dt.to_period("M")).transform('mean')

# Display the updated DataFrame
print(df1.info())
merged_df_2003.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   DATE                         241 non-null    datetime64[ns]
 1   priceindex                   241 non-null    float64
 2   percapitagdp                 241 non-null    float64
 3   personalincome               241 non-null    float64
 4   unemprate                    241 non-null    float64
 5   fedfundsinterestrate         241 non-null    float64
 6   fixmortgagerate15years       241 non-null    float64
 7   personalsavingrate           241 non-null    float64
 8   laborforceparticipationrate  241 non-null    float64
 9   workingpopulation            241 non-null    float64
 10  medianhouseincome            20 non-null     float64
 11  energyindex                  241 non-null    float64
 12  constructionspending         241 non-null    float64
 13  totalnewhouseunits           241 non-null    float64
 14  housingsubsidies             20 non-null     float64
 15  totalhouseholds              21 non-null     float64
dtypes: datetime64[ns](1), float64(15)
memory usage: 30.2 KB
None

,DATE,priceindex,percapitagdp,personalincome,unemprate,fedfundsinterestrate,fixmortgagerate15years,personalsavingrate,laborforceparticipationrate,workingpopulation,medianhouseincome,energyindex,constructionspending,totalnewhouseunits,housingsubsidies,totalhouseholds
0,2003-01-01,128.461,50462.000000,10710.4,5.8,1.24,5.3040,5.3,66.4,1.856353e+08,65860.0,79.454166,863855.0,1654.0,25.93,111278.0
1,2003-02-01,129.355,50573.333333,10674.0,5.9,1.26,5.2200,5.2,66.4,1.858697e+08,NaN,90.889264,859225.0,1688.0,NaN,NaN
2,2003-03-01,130.148,50684.666667,10696.5,5.9,1.25,5.0650,4.9,66.3,1.860851e+08,NaN,80.592195,851132.0,1638.0,NaN,NaN
3,2003-04-01,130.884,50796.000000,10752.7,6.0,1.26,5.1175,5.0,66.4,1.864708e+08,NaN,70.847197,859459.0,1662.0,NaN,NaN
4,2003-05-01,131.735,51034.666667,10832.0,6.1,1.26,4.8600,5.3,66.4,1.866491e+08,NaN,72.878676,866814.0,1733.0,NaN,NaN
5,2003-06-01,132.649,51273.333333,10860.6,6.3,1.22,4.6275,5.1,66.5,1.868007e+08,NaN,76.204120,880865.0,1641.0,NaN,NaN
6,2003-07-01,133.777,51512.000000,10991.1,6.2,1.01,4.9675,5.9,66.2,1.870665e+08,NaN,75.261384,891264.0,1680.0,NaN,NaN
7,2003-08-01,134.969,51670.000000,11066.7,6.1,1.03,5.5880,5.7,66.1,1.873040e+08,NaN,77.177782,901839.0,1570.0,NaN,NaN
8,2003-09-01,136.294,51828.000000,10940.8,6.1,1.01,5.4575,4.9,66.1,1.875390e+08,NaN,71.984238,911589.0,1719.0,NaN,NaN
9,2003-10-01,137.531,51986.000000,10982.3,6.0,1.01,5.2740,5.0,66.1,1.877385e+08,NaN,75.717675,925732.0,1728.0,NaN,NaN

In [ ]:
# forward filling the data
merged_df_2003['medianhouseincome'].fillna(method='ffill', inplace=True)
merged_df_2003['housingsubsidies'].fillna(method='ffill', inplace=True)
merged_df_2003['totalhouseholds'].fillna(method='ffill', inplace=True)




merged_df_2003.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   DATE                         241 non-null    datetime64[ns]
 1   priceindex                   241 non-null    float64
 2   percapitagdp                 241 non-null    float64
 3   personalincome               241 non-null    float64
 4   unemprate                    241 non-null    float64
 5   fedfundsinterestrate         241 non-null    float64
 6   fixmortgagerate15years       241 non-null    float64
 7   personalsavingrate           241 non-null    float64
 8   laborforceparticipationrate  241 non-null    float64
 9   workingpopulation            241 non-null    float64
 10  medianhouseincome            241 non-null    float64
 11  energyindex                  241 non-null    float64
 12  constructionspending         241 non-null    float64
 13  totalnewhouseunits           241 non-null    float64
 14  housingsubsidies             241 non-null    float64
 15  totalhouseholds              241 non-null    float64
dtypes: datetime64[ns](1), float64(15)
memory usage: 30.2 KB

In [ ]:
final_dataset=merged_df_2003.copy()
final_dataset.head()

,DATE,priceindex,percapitagdp,personalincome,unemprate,fedfundsinterestrate,fixmortgagerate15years,personalsavingrate,laborforceparticipationrate,workingpopulation,medianhouseincome,energyindex,constructionspending,totalnewhouseunits,housingsubsidies,totalhouseholds
0,2003-01-01,128.461,50462.000000,10710.4,5.8,1.24,5.3040,5.3,66.4,1.856353e+08,65860.0,79.454166,863855.0,1654.0,25.93,111278.0
1,2003-02-01,129.355,50573.333333,10674.0,5.9,1.26,5.2200,5.2,66.4,1.858697e+08,65860.0,90.889264,859225.0,1688.0,25.93,111278.0
2,2003-03-01,130.148,50684.666667,10696.5,5.9,1.25,5.0650,4.9,66.3,1.860851e+08,65860.0,80.592195,851132.0,1638.0,25.93,111278.0
3,2003-04-01,130.884,50796.000000,10752.7,6.0,1.26,5.1175,5.0,66.4,1.864708e+08,65860.0,70.847197,859459.0,1662.0,25.93,111278.0
4,2003-05-01,131.735,51034.666667,10832.0,6.1,1.26,4.8600,5.3,66.4,1.866491e+08,65860.0,72.878676,866814.0,1733.0,25.93,111278.0

In [ ]:
# saving a DataFrame to a CSV file
final_dataset.to_csv('/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/housing_data.csv', index=False)

In [ ]:
df2=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ALMAX/Home LLC/Datasets/housing_data.csv')
df2.head()

,DATE,priceindex,percapitagdp,personalincome,unemprate,fedfundsinterestrate,fixmortgagerate15years,personalsavingrate,laborforceparticipationrate,workingpopulation,medianhouseincome,energyindex,constructionspending,totalnewhouseunits,housingsubsidies,totalhouseholds
0,2003-01-01,128.461,50462.000000,10710.4,5.8,1.24,5.3040,5.3,66.4,1.856353e+08,65860.0,79.454166,863855.0,1654.0,25.93,111278.0
1,2003-02-01,129.355,50573.333333,10674.0,5.9,1.26,5.2200,5.2,66.4,1.858697e+08,65860.0,90.889264,859225.0,1688.0,25.93,111278.0
2,2003-03-01,130.148,50684.666667,10696.5,5.9,1.25,5.0650,4.9,66.3,1.860851e+08,65860.0,80.592195,851132.0,1638.0,25.93,111278.0
3,2003-04-01,130.884,50796.000000,10752.7,6.0,1.26,5.1175,5.0,66.4,1.864708e+08,65860.0,70.847197,859459.0,1662.0,25.93,111278.0
4,2003-05-01,131.735,51034.666667,10832.0,6.1,1.26,4.8600,5.3,66.4,1.866491e+08,65860.0,72.878676,866814.0,1733.0,25.93,111278.0